[package]
name = "embed"
version = "0.1.0"
authors = ["kir4ik <vlados.linkoln@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.0"

[lib]
name = "embed"
crate-type = ["dylib"]
